-- Lv 3. 물고기 종류 별 대어 찾기
SELECT I.ID, N.FISH_NAME, I.LENGTH
FROM (
    SELECT
        ID,
        FISH_TYPE,
        LENGTH,
        TIME,
        RANK() OVER (PARTITION BY FISH_TYPE ORDER BY LENGTH DESC) AS RNK
    FROM FISH_INFO
) I
JOIN FISH_NAME_INFO N ON I.FISH_TYPE = N.FISH_TYPE
WHERE I.RNK = 1
ORDER BY I.ID