-- 코드를 작성해주세요
SELECT I.ID, N.FISH_NAME, I.LENGTH
FROM FISH_INFO I
JOIN ( # FISH_TYPE 별로 LENGTH가 최대인 테이블 먼저 생성
    SELECT FISH_TYPE, MAX(LENGTH) AS LENGTH
    FROM FISH_INFO
    GROUP BY FISH_TYPE 
) ML ON I.FISH_TYPE = ML.FISH_TYPE AND I.LENGTH = ML.LENGTH
JOIN FISH_NAME_INFO N ON I.FISH_TYPE = N.FISH_TYPE  # 물고기 이름을 알아내기 위해 FISH_NAME_INFO 테이블과 JOIN
ORDER BY I.ID ASC
