-- IF문 처리
-- (1) IFNULL(컬럼명, 대체값) 
-- (2) IF(조건식, 참인 경우 반환값, 거짓인 경우 반환값) 
-- (3)   
-- CASE 
--     WHEN FREEZER_YN IS NULL THEN 'N'
--     ELSE FREEZER_YN
-- END AS FREEZER_YN

SELECT WAREHOUSE_ID, WAREHOUSE_NAME, ADDRESS, 
    IFNULL(FREEZER_YN, 'N') AS FREEZER_YN
FROM FOOD_WAREHOUSE
WHERE WAREHOUSE_NAME LIKE '%경기%'
ORDER BY WAREHOUSE_ID ASC