-- 특정 월만 꺼내는방법 MONTH() 함수 사용
-- 연도는 YEAR()
-- 일자는 보통 DAY() / 

-- WHERE ... IN (서브쿼리) 형식
SELECT MONTH(START_DATE), CAR_ID, COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE START_DATE >= '2022-08-01' AND 
    START_DATE <= '2022-10-31' AND 
    CAR_ID IN (
        SELECT CAR_ID 
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE START_DATE >= '2022-08-01' AND 
            START_DATE <= '2022-10-31'
        GROUP BY CAR_ID 
        HAVING COUNT(*) >= 5
    )
GROUP BY MONTH(START_DATE), CAR_ID
ORDER BY MONTH(START_DATE) ASC, CAR_ID DESC